# -*- coding: utf-8 -*-
"""code for searching

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14mzouQuDQe50Fu2rbA_EsIOXAqxeB95t
"""

"""no.4.Write a Python program to store the employee id of employee in array who attended
training program in random order. Write function for searching whether particular
student attended training program or not, using Linear search and Sentinel search. """

def Linsearch(arr,key):     #for linear search
    for i in range(len(arr)):
        if arr[i] == key:
            return i

def Sentsearch(arr,key):     #for sentinel search
    l = len(arr)
    arr.append(key)
    i = 0
    while(arr[i]!=key):
        i = i+1
         return i
    else:
       pass
def Binsearch(arr,key):    #for binary search
    low = 0
    high = len(arr)-1
    m = 0
    while(low<=high):
        m =(low+high)/2	
        if(key<arr[m]):
            high = m-1
        elif(key>arr[m]):
            low = m+1
        else:
             return m              


print("\nEnter number of students")
n = int(input())
array = []
i=0
for i in range(n):
    print("\n Enter roll number of student %d: "%(i+1))
    item = int(input())
    array.append(item)

print("The Roll Numbers of Students are \n")
print(array)
while(True):
    print("Select your choice")
    print("\n 1. Linear Search")
    print("\n 2. Sentinel Search")
    print("\n 3. Binary Search")
    print("\n Enter your choice: ")
    choice = int(input())
    if(choice == 1):
        print("\n Enter the roll number you want to search  ")
        key = int(input())
        location = Linsearch(array,key)
        if(location !=-1):
            print("Yes, the student attended the program ")
        else:
            print("No, the student has not attended the program ")
    elif(choice == 2):
        print("\n Enter the roll number you want to search  ")
        key = int(input())
        location = Sentsearch(array,key)
        if(location !=-1):
            print("Yes, the student attended the program")
        else:
            print("No, the student has not attended the program")
    elif(choice == 3):
        print("\n Enter the roll number you want to search ")
        key = int(input())
        location = Binsearch(array,key)
        if(location !=-1):
            print("Yes, the student attended program")
        else:
            print("No, the student has not attended program")
    else:
        print("You are exitted");
        break